### PR TITLE
Handle case where sourceText is undefined.

### LINKED ISSUE #2: Invalid .json file
Hello @thlorenz -Great tool! I was hoping to test some code through it. However, I keep running into:
```
Invalid TurboFan JSON file
error: JSON.parse: unexpected character at line 2 column 11 of the JSON data
```

Running: `node --trace-turbo app.js` and then `turbolizer` in the same folder.
Any ideas?

### PR DESCRIPTION
**Pull request by Manouchehri**
Fixes #2.

### CODE REVIEW

**Comment by aichholzer** [comment]
@Manouchehri -Easiest fix I have ever seen. 👍 
However, I patched my local installations with your proposed fixes and I still get the same error. 🤔 

Tried with:
```js
{
  node: '10.12.0',
  v8: '6.8.275.32-node.35'
}
```
```js
{
  node: '10.14.2',
  v8: '6.8.275.32-node.45'
}
```
```js
{
  node: '11.4.0',
  v8: '7.0.276.38-node.13'
}
```

**Comment by Manouchehri** [comment]
Could you post your JSON trace? I was using 7.0.276.40.

**Comment by aichholzer** [comment]
@Manouchehri -Files are [here](https://www.dropbox.com/sh/k9h1eoihbmo9kju/AAAaAQQwhkP7GY30qaMZJCm_a?dl=0).

**Comment by Manouchehri** [comment]
image
Loads fine here!

**Comment by aichholzer** [comment]
@Manouchehri -Interesting... Now I wonder what I am possibly doing wrong...
```
$> node --trace-turbo app.js
$> turbolizer
```
and... Error.
Any particular version you are running, is the above pre or post applying your suggested patch?

**Comment by thlorenz** [comment]
Thanks patched and published new version (better late than never).

**Pull request merged**
